print("this is the first code")
print("this is the first code")
print("this is the first code")
print(2+3)
print("this is the first code")
print(2+3)
print("this is the first code")
print("this is the first code")
print(2+3)
print("this is the first code")
